slicer_download_maintenance:
  enabled: true
  info_url: https://discourse.slicer.org/t/maintenance-of-download-slicer-org-slicer-kitware-com-and-slicer-packages-kitware-com-planned-for-june-27th-2023-2-00pm-to-4-00pm-et/30250
  date: June 27th, 2023
  start_time: 2:00 PM
  end_time: 4:00 PM
  duration: two hours
  timezone: ET
