slicer_download_maintenance:
  enabled: true
  info_url: https://discourse.slicer.org/t/maintenance-of-download-slicer-org-slicer-kitware-com-and-slicer-packages-kitware-com-planned-for-march-28th-2024-3-30pm-to-5-00pm-et/35155
  date: March 28th, 2024
  start_time: 3:30 PM
  end_time: 5:00 PM
  duration: 1.5 hours
  timezone: ET
