# Documentation at https://www.netlify.com/docs/netlify-toml-reference/
[build]
  command = "jekyll build"
  publish = "_site/"

# Copied from https://answers.netlify.com/t/jekyll-site-uses-absolute-urls-deploy-previews-navigate-to-main-site/8441/12
[context.deploy-preview]
  command = "printf \"url: %s\" \"$DEPLOY_PRIME_URL\" > _config_netlify.yml; jekyll build --config _config.yml,_config_netlify.yml"

[context.deploy-download-preview]
  command = "printf \"slicer_download_url: %s\" \"$DEPLOY_PRIME_URL/download.html\nslicer_download_mock_enabled: true\" > _config_netlify.yml; jekyll build --config _config.yml,_config_download.yml,_config_netlify.yml"
